packages:
  - 'apps/*'
  - 'packages/*'
  - 'native/*'
  - 'tooling/*'
  - 'connectors/*'

allowBuilds:
  '@google/genai': false
  better-sqlite3: false
  electron-winstaller: false
  esbuild: true
  protobufjs: false
