#!/usr/bin/env python3
"""Kiểm chứng Q3: Thao tác nào BUỘC gắn cờ irreversible trong Notion API."""

import json
import sys
import pathlib
import datetime
from common import (
    get_token, get_workspace_info, create_page, get_page,
    set_page_archived, raw_api_call, DATA_DIR
)

def run():
    print("=== Chạy kiểm chứng Q3: Thao tác Irreversible ===")
    tok_a = get_token("A")
    info_a = get_workspace_info("A")
    db_a_id = info_a["databases"][0]["id"]

    results = {
        "comments_reversibility": {},
        "block_archive_unarchive": {},
        "irreversible_operations_summary": []
    }

    # 1. Tạo test page
    status, _, page = create_page(
        tok_a,
        parent={"database_id": db_a_id},
        properties={"Name": {"title": [{"text": {"content": "SP1 Q3 Irreversible Test Task"}}]}},
        children=[
            {"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"type": "text", "text": {"content": "Test block for archival"}}]}}
        ],
        category="q3_create_page"
    )
    page_id = page["id"]

    # 2. Thử nghiệm Comment API: Có thể xóa comment không?
    print("\n--- 1. Kiểm tra Comment API ---")
    st_c, _, c_data = raw_api_call(
        tok_a, "POST", "/comments",
        body={
            "parent": {"page_id": page_id},
            "rich_text": [{"text": {"content": "Test comment generated by Desktop Assistant Agent"}}]
        },
        log_category="q3_create_comment"
    )
    print(f"   Tạo comment: HTTP {st_c}")
    comment_id = c_data.get("id") if st_c == 200 else None

    can_delete_comment = False
    delete_err = None
    if comment_id:
        # Thử DELETE /v1/comments/:id
        st_del, _, del_resp = raw_api_call(tok_a, "DELETE", f"/comments/{comment_id}", log_category="q3_delete_comment")
        print(f"   Thử DELETE /v1/comments/{comment_id}: HTTP {st_del}")
        
        # Thử PATCH /v1/comments/:id (archived: true)
        st_patch, _, patch_resp = raw_api_call(tok_a, "PATCH", f"/comments/{comment_id}", body={"archived": True}, log_category="q3_patch_comment")
        print(f"   Thử PATCH /v1/comments/{comment_id}: HTTP {st_patch}")
        
        results["comments_reversibility"] = {
            "comment_id": comment_id,
            "create_status": st_c,
            "delete_status": st_del,
            "delete_response": del_resp,
            "patch_status": st_patch,
            "patch_response": patch_resp,
            "conclusion": "Notion API KHÔNG CÓ endpoint xóa hoặc archive comment. Mọi thao tác thêm comment là HOÀN TOÀN IRREVERSIBLE."
        }
    else:
        results["comments_reversibility"] = {
            "create_status": st_c,
            "error": c_data
        }

    # 3. Thử nghiệm Block archival và unarchival
    print("\n--- 2. Kiểm tra Xóa / Khôi phục Block con ---")
    # Lấy block con
    _, _, child_blocks = raw_api_call(tok_a, "GET", f"/blocks/{page_id}/children", log_category="q3_get_children")
    block_id = child_blocks["results"][0]["id"]
    print(f"   Block con ID: {block_id}")

    # Xóa block con: DELETE /v1/blocks/:id (Notion biến block thành archived: true)
    st_b_del, _, del_b_data = raw_api_call(tok_a, "DELETE", f"/blocks/{block_id}", log_category="q3_delete_block")
    print(f"   DELETE /v1/blocks/{block_id}: HTTP {st_b_del}, archived={del_b_data.get('archived')}")

    # Thử khôi phục block con: PATCH /v1/blocks/:id {"archived": false}
    st_b_restore, _, rest_b_data = raw_api_call(tok_a, "PATCH", f"/blocks/{block_id}", body={"archived": False}, log_category="q3_restore_block")
    print(f"   PATCH /v1/blocks/{block_id} (archived=false): HTTP {st_b_restore}")

    results["block_archive_unarchive"] = {
        "block_id": block_id,
        "delete_block_status": st_b_del,
        "delete_block_archived": del_b_data.get("archived"),
        "restore_block_status": st_b_restore,
        "restore_block_response": rest_b_data,
        "conclusion": "Block con có thể archive qua DELETE /v1/blocks/:id và unarchive qua PATCH /v1/blocks/:id với {'archived': false}." if st_b_restore == 200 else "Block con KHÔNG thể unarchive qua API."
    }

    # 4. Tổng kết danh mục thao tác bắt buộc gắn cờ irreversible
    results["irreversible_operations_summary"] = [
        {
            "operation": "create_comment",
            "reason": "Notion API không hỗ trợ DELETE hay PATCH trên đối tượng comment. Comment tạo ra sẽ tồn tại vĩnh viễn trên page.",
            "flag": "IRREVERSIBLE"
        },
        {
            "operation": "assign_user (Assignee / People property)",
            "reason": "Gán người dùng kích hoạt thông báo push/email của Notion ngay lập tức. Thao tác bù trừ (gỡ user) khôi phục property nhưng không thể thu hồi email/thông báo đã gửi.",
            "flag": "REVERSIBLE_WITH_IRREVERSIBLE_SIDE_EFFECTS"
        },
        {
            "operation": "permanent_page_deletion",
            "reason": "Notion API không hỗ trợ xóa vĩnh viễn (chỉ archive). Tuy nhiên nếu người dùng dọn rác thùng rác (empty trash) trên Notion GUI, API trả về 404 và không thể unarchive.",
            "flag": "EXTERNAL_PERMANENT_LOSS"
        },
        {
            "operation": "database_schema_drop_property",
            "reason": "Nếu xóa một property của database (ví dụ qua PATCH /databases), toàn bộ dữ liệu của cột đó trên mọi dòng bị mất, không thể bù trừ tự động bằng snapshot của một dòng.",
            "flag": "IRREVERSIBLE"
        }
    ]

    # Dọn dẹp test page
    set_page_archived(tok_a, page_id, True, category="q3_cleanup")

    out_file = DATA_DIR / "q3_irreversible_results.json"
    out_file.write_text(json.dumps(results, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n✓ Hoàn tất Q3. Kết quả lưu tại: {out_file}")

if __name__ == "__main__":
    run()
