[package]
name = "desktop-window-win32"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16.14", default-features = false, features = ["napi4"] }
parking_lot = "0.12"
napi-derive = "2.16.13"
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_Threading",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
napi-build = "1.2.1"
